tap "homebrew/cask"
tap "homebrew/cask-fonts"
cask_args appdir: "~/Applications"

brew "awscli"
# brew "aws-sam-cli"
brew "brew-cask-completion"
brew "ctags"
brew "firebase-cli"
brew "ffmpeg"
brew "gh"
brew "graphviz"
brew "grep"
brew "jq"
brew "neovim"
# brew "nkf"
brew "mas"
brew "mysql"
brew "slack"
brew "starship"
# brew "tfenv"
brew "the_silver_searcher"
brew "tree"
brew "wget"
brew "zsh-completions"
brew "1password"

# neovimのプラグインで利用
brew "ripgrep"
brew "fd"

# ブラウザ
cask "google-chrome"

# 開発系
cask "altair-graphql-client"
# cask "android-studio"
# cask "aws-vault"
cask "obsidian"
cask "docker"
# cask "flutter"
cask "figma"
cask "iterm2"
cask "karabiner-elements"
# cask "mysqlworkbench"
cask "nosql-workbench"
cask "raycast"
cask "skitch"
cask "visual-studio-code"

# その他
cask "font-fira-code-nerd-font"
