# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# プラグインの遅延読み込み
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# apply = ["defer"] で遅延読み込み対象のプラグインを指定
[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

# シンタックスハイライト
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

# Oh My Zsh の Git プラグインのみをロード
[plugins.ohmyzsh-lib-git]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
apply = ["source", "defer"]

[plugins.ohmyzsh-plugins-git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"
apply = ["source", "defer"]